window.CreatureTypes = {
    normal: "normal",
    armoured: "armoured",
    flying: "flying",
    grounded: "grounded",
}

window.Creatures = {
    "s001": {
        name: "Dogmeat",
        description: "The radiation has changed your K9 just a bit!",
        type: CreatureTypes.flying,
        src: "/WastelandChronicles/images/characters/Creatures/silvercreature_1.png",
        icon: "/WastelandChronicles/images/icons/flying.png",
        actions: [ "damage2", "damage3", "empoweredStatus", "weakStatus" ],
    },
    "s002": {
        name: "Skeleton",
        description: "All bones and not play!!",
        type: CreatureTypes.normal,
        src: "/WastelandChronicles/images/characters/Creatures/silvercreature_2.png",
        icon: "/WastelandChronicles/images/icons/normal.png",
        actions: [ "damage1", "damage2", "weakStatus" ],
    },
    "s003": {
        name: "Hulk Skeleton",
        description: "Is it the Hulk or the abomination?",
        type: CreatureTypes.armoured,
        src: "/WastelandChronicles/images/characters/Creatures/silvercreature_3.png",
        icon: "/WastelandChronicles/images/icons/armoured.png",
        actions: [ "damage2", "damage3", "damage4", "empoweredStatus" ],
    },    
    "r001": {
        name: "red dude",
        description: "He's red and wear's a belt!",
        type: CreatureTypes.normal,
        src: "/WastelandChronicles/images/characters/Creatures/redcreature_1.png",
        icon: "/WastelandChronicles/images/icons/normal.png",
        actions: [ "damage1" ],
    },    
    "r002": {
        name: "War Hog!",
        description: "Beefed Up and angry wolverine!",
        type: CreatureTypes.normal,
        src: "/WastelandChronicles/images/characters/Creatures/redcreature_2.png",
        icon: "/WastelandChronicles/images/icons/normal.png",
        actions: [ "damage2" ],
    },
    "r003": {
        name: "Pig",
        description: "Wierd dude who got glass stuck in him!",
        type: CreatureTypes.grounded,
        src: "/WastelandChronicles/images/characters/Creatures/redcreature_3.png",
        icon: "/WastelandChronicles/images/icons/grounded.png",
        actions: [ "damage1" ],
    },
    "r004": {
        name: "Boar",
        description: "Ant on steriods!",
        type: CreatureTypes.armoured,
        src: "/WastelandChronicles/images/characters/Creatures/redcreature_4.png",
        icon: "/WastelandChronicles/images/icons/armoured.png",
        actions: [ "damage1" ],
    },
    "r005": {
        name: "Rabbit",
        description: "Flying Demon Rabbit!",
        type: CreatureTypes.flying,
        src: "/WastelandChronicles/images/characters/Creatures/redcreature_5.png",
        icon: "/WastelandChronicles/images/icons/flying.png",
        actions: [ "damage3" ],
    },
    "b001": {
        name: "Witch Doctor",
        description: "Lizard with bad breathe!!",
        type: CreatureTypes.normal,
        src: "/WastelandChronicles/images/characters/Creatures/blackcreature_1.png",
        icon: "/WastelandChronicles/images/icons/normal.png",
        actions: [ "damage1" ],
    },
       "b002": {
        name: "Unicorn Rabbit",
        description: "Mutated Enclave! RUN!!",
        type: CreatureTypes.grounded,
        src: "/WastelandChronicles/images/characters/Creatures/blackcreature_2.png",
        icon: "/WastelandChronicles/images/icons/grounded.png",
        actions: [ "damage1" ],
    },
    "b003": {
        name: "Frogger!",
        description: "HE's been ran over a few too many times!",
        type: CreatureTypes.grounded,
        src: "/WastelandChronicles/images/characters/Creatures/blackcreature_3.png",
        icon: "/WastelandChronicles/images/icons/grounded.png",
        actions: [ "damage2" ],
    },
    "b004": {
        name: "Kaine The Destroyer!",
        description: "Give him/Her a cuddle!!",
        type: CreatureTypes.armoured,
        src: "/WastelandChronicles/images/characters/Creatures/blackcreature_4.png",
        icon: "/WastelandChronicles/images/icons/armoured.png",
        actions: [ "damage1" ],
    },
    "b005": {
        name: "Golem",
        description: "We are legion!",
        type: CreatureTypes.armoured,
        src: "/WastelandChronicles/images/characters/Creatures/blackcreature_5.png",
        icon: "/WastelandChronicles/images/icons/armoured.png",
        actions: [ "damage4" ],
    },
    "x001": {
        name: "BIG WORM!",
        description: "CRAZY BIG EVIL WORM!!",
        type: CreatureTypes.armoured,
        src: "/WastelandChronicles/images/characters/Creatures/worm.png",
        icon: "/WastelandChronicles/images/icons/armoured.png",
        actions: [ "bite","lick" ],
    },
    "x002": {
        name: "Rainbow Bunny!!",
        description: "Big Pointy Teeth!!!",
        type: CreatureTypes.armoured,
        src: "/WastelandChronicles/images/characters/Creatures/rainbowbunny.png",
        icon: "/WastelandChronicles/images/icons/armoured.png",
        actions: [ "bite","lick" ],
    }
}